export const SPHERE_CONFIGS = [
  {
    email: "olivia.morgan@example.com",
    name: "Olivia",
    message: "Keep going 💪",
    roughness: 0.25,
    metalness: 0.1,
    face: "L",
    diffuse: "A",
    normal: "A",
  },
  {
    email: "liam.carter@example.com",
    name: "Liam",
    message: "Great vibes",
    roughness: 0.12,
    metalness: 0.9,
    face: "A",
    diffuse: "B",
    normal: "C",
  },
  {
    email: "emma.hughes@example.com",
    name: "Emma",
    message: "Keep shining",
    roughness: 0.2,
    metalness: 0.8,
    face: "B",
    diffuse: "C",
    normal: "D",
  },
  {
    email: "noah.parker@example.com",
    name: "Noah",
    message: "Love this 💙",
    roughness: 0.35,
    metalness: 0.3,
    face: "C",
    diffuse: "D",
    normal: "B",
  },
  {
    email: "avaBena.bennett@example.com",
    name: "Ava",
    message: "Amazing day",
    roughness: 0.15,
    metalness: 0.75,
    face: "H",
    diffuse: "B",
    normal: "B",
  },
  {
    email: "ethan.foster@example.com",
    name: "Ethan",
    message: "Let's go 🚀",
    roughness: 0.2,
    metalness: 0.8,
    face: "E",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "mia.turner@example.com",
    name: "Mouse",
    message: "❤️",
    roughness: 0.3,
    metalness: 0.4,
    face: "F",
    diffuse: "B",
    normal: "B",
  },
  {
    email: "lucass.hesxa@example.com",
    name: "Luca",
    message: "Never stop",
    roughness: 0.18,
    metalness: 0.85,
    face: "B",
    diffuse: "D",
    normal: "D",
  },
  {
    email: "charlotte.brooks@example.com",
    name: "Charlie",
    message: "Hello world 👋",
    roughness: 0.22,
    metalness: 0.6,
    face: "H",
    diffuse: "B",
    normal: "C",
  },
  {
    email: "henry.collins@example.com",
    name: "Henry",
    message: "Nice event",
    roughness: 0.28,
    metalness: 0.2,
    face: "I",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "amelia.ward@example.com",
    name: "Amelia",
    message: "Beautiful",
    roughness: 0.15,
    metalness: 0.9,
    face: "J",
    diffuse: "A",
    normal: "B",
  },
  {
    email: "james.reed@example.com",
    name: "James",
    message: "Good luck 🍀",
    roughness: 0.32,
    metalness: 0.3,
    face: "K",
    diffuse: "C",
    normal: "D",
  },
  {
    email: "harper.gray@example.com",
    name: "Harper",
    message: "Feeling good",
    roughness: 0.25,
    metalness: 0.7,
    face: "A",
    diffuse: "B",
    normal: "B",
  },
  {
    email: "benjamin.price@example.com",
    name: "Ben",
    message: "Awesome",
    roughness: 0.1,
    metalness: 0.95,
    face: "B",
    diffuse: "A",
    normal: "C",
  },
  {
    email: "evelyn.mitchell@example.com",
    name: "Eve",
    message: "Stay calm",
    roughness: 0.4,
    metalness: 0.1,
    face: "C",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "daniel.baker@example.com",
    name: "Daniel",
    message: "Keep going 💪",
    roughness: 0.2,
    metalness: 0.85,
    face: "D",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "sofia.long@example.com",
    name: "Sofia",
    message: "Dream big",
    roughness: 0.3,
    metalness: 0.5,
    face: "E",
    diffuse: "A",
    normal: "C",
  },
  {
    email: "jackson.rivera@example.com",
    name: "Jack",
    message: "Enjoy it",
    roughness: 0.15,
    metalness: 0.7,
    face: "F",
    diffuse: "C",
    normal: "D",
  },
  {
    email: "ella.scott@example.com",
    name: "Ella",
    message: "So lovely",
    roughness: 0.25,
    metalness: 0.4,
    face: "B",
    diffuse: "A",
    normal: "B",
  },
  {
    email: "logan.cook@example.com",
    name: "Logan",
    message: "Amazing work 🚀",
    roughness: 0.22,
    metalness: 0.8,
    face: "H",
    diffuse: "B",
    normal: "A",
  },
];
