export const SPHERE_CONFIGS = [
  {
    email: "olivia.morgan@example.com",
    roughness: 0.25,
    metalness: 0.1,
    face: "L",
    diffuse: "A",
    normal: "A",
  },
  {
    email: "liam.carter@example.com",
    roughness: 0.12,
    metalness: 0.9,
    face: "A",
    diffuse: "B",
    normal: "C",
  },
  {
    email: "emma.hughes@example.com",
    roughness: 0.2,
    metalness: 0.8,
    face: "B",
    diffuse: "C",
    normal: "D",
  },
  {
    email: "noah.parker@example.com",
    roughness: 0.35,
    metalness: 0.3,
    face: "C",
    diffuse: "D",
    normal: "B",
  },
  {
    email: "ava.bennett@example.com",
    roughness: 0.15,
    metalness: 0.75,
    face: "D",
    diffuse: "A",
    normal: "D",
  },
  {
    email: "ethan.foster@example.com",
    roughness: 0.2,
    metalness: 0.8,
    face: "E",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "mia.turner@example.com",
    roughness: 0.3,
    metalness: 0.4,
    face: "F",
    diffuse: "B",
    normal: "B",
  },
  {
    email: "lucas.hayes@example.com",
    roughness: 0.18,
    metalness: 0.85,
    face: "B",
    diffuse: "C",
    normal: "D",
  },
  {
    email: "charlotte.brooks@example.com",
    roughness: 0.22,
    metalness: 0.6,
    face: "H",
    diffuse: "B",
    normal: "C",
  },
  {
    email: "henry.collins@example.com",
    roughness: 0.28,
    metalness: 0.2,
    face: "I",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "amelia.ward@example.com",
    roughness: 0.15,
    metalness: 0.9,
    face: "J",
    diffuse: "A",
    normal: "B",
  },
  {
    email: "james.reed@example.com",
    roughness: 0.32,
    metalness: 0.3,
    face: "K",
    diffuse: "C",
    normal: "D",
  },
  {
    email: "harper.gray@example.com",
    roughness: 0.25,
    metalness: 0.7,
    face: "A",
    diffuse: "B",
    normal: "B",
  },
  {
    email: "benjamin.price@example.com",
    roughness: 0.1,
    metalness: 0.95,
    face: "B",
    diffuse: "A",
    normal: "C",
  },
  {
    email: "evelyn.mitchell@example.com",
    roughness: 0.4,
    metalness: 0.1,
    face: "C",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "daniel.baker@example.com",
    roughness: 0.2,
    metalness: 0.85,
    face: "D",
    diffuse: "D",
    normal: "A",
  },
  {
    email: "sofia.long@example.com",
    roughness: 0.3,
    metalness: 0.5,
    face: "E",
    diffuse: "A",
    normal: "C",
  },
  {
    email: "jackson.rivera@example.com",
    roughness: 0.15,
    metalness: 0.7,
    face: "F",
    diffuse: "C",
    normal: "D",
  },
  {
    email: "ella.scott@example.com",
    roughness: 0.25,
    metalness: 0.4,
    face: "G",
    diffuse: "A",
    normal: "B",
  },
  {
    email: "logan.cook@example.com",
    roughness: 0.22,
    metalness: 0.8,
    face: "H",
    diffuse: "B",
    normal: "A",
  },
];
